/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-05-31 14:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      com.thinking.machines.hr.beans.ErrorBean errorBean = null;
      errorBean = (com.thinking.machines.hr.beans.ErrorBean) _jspx_page_context.getAttribute("errorBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (errorBean == null){
        errorBean = new com.thinking.machines.hr.beans.ErrorBean();
        _jspx_page_context.setAttribute("errorBean", errorBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.thinking.machines.hr.beans.AdministrationBean administrationBean = null;
      administrationBean = (com.thinking.machines.hr.beans.AdministrationBean) _jspx_page_context.getAttribute("administrationBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (administrationBean == null){
        administrationBean = new com.thinking.machines.hr.beans.AdministrationBean();
        _jspx_page_context.setAttribute("administrationBean", administrationBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang='en'>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset='utf-8'>\r\n");
      out.write("<title>HR application</title>\r\n");
      out.write("<script>\r\n");
      out.write("function preventBack() { window.history.forward(); }\r\n");
      out.write("setTimeout(\"preventBack()\", 0);\r\n");
      out.write("window.onunload = function () { null };\r\n");
      out.write("function validateForm(frm)\r\n");
      out.write("{\r\n");
      out.write("var username=frm.username.value.trim();\r\n");
      out.write("var password=frm.password.value.trim();\r\n");
      out.write("var flag=true;\r\n");
      out.write("var firstFocus=false;\r\n");
      out.write("var usernameErrorSection=document.getElementById('usernameErrorSection');\r\n");
      out.write("usernameErrorSection.innerHTML='';\r\n");
      out.write("var passwordErrorSection=document.getElementById('passwordErrorSection');\r\n");
      out.write("passwordErrorSection.innerHTML='';\r\n");
      out.write("if(username.length==0)\r\n");
      out.write("{\r\n");
      out.write("usernameErrorSection.innerHTML='required';\r\n");
      out.write("firstFocus=true;\r\n");
      out.write("frm.username.focus();\r\n");
      out.write("flag=false;\r\n");
      out.write("}\r\n");
      out.write("if(password.length==0)\r\n");
      out.write("{\r\n");
      out.write("passwordErrorSection.innerHTML='required';\r\n");
      out.write("if(!firstFocus)frm.password.focus();\r\n");
      out.write("flag=false;\r\n");
      out.write("}\r\n");
      out.write("return flag;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Main container starts here -->\r\n");
      out.write("<div style='width:90hw;height:auto;border: 1px solid black'>\r\n");
      out.write("<!-- header starts here -->\r\n");
      out.write("<div style='margin:5px;width:90hw;height:auto;border: 1px solid black'>\r\n");
      out.write("<img src='/styleone/images/logo.png'style='float:left'>\r\n");
      out.write("<div style='margin-top:9px;margin-botton:9px;font-size:28pt'>ABS COMPANY</div>\r\n");
      out.write("</div> <!-- header ends here -->\r\n");
      out.write("<!-- Container section starts here -->\r\n");
      out.write("<div style='width:90hw;height:70vh;margin:5px;border: 1px solid white'>\r\n");
      out.write("<!-- Inner panel starts here -->\r\n");
      out.write("<div style='height:65vh;margin-left:5px;margin-right:5px;margin-top:5px;margin-botton:5px;padding:5px;border:1px solid black'>\r\n");
      out.write("<center>\r\n");
      out.write("<h1>Administration</h1>\r\n");
      out.write("<form method='post' style='margin-left:380px;margin-right:380px;border:1px solid black;padding:20px;' action='/stylefour/Login.jsp' onsubmit='return validateForm(this)'>\r\n");
      out.write("<span style='color:red'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorBean.error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><br>\r\n");
      out.write("Username  \r\n");
      out.write("<input type='text' id='username' name='username' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${administratorBean.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' maxlength='20'>\r\n");
      out.write("<span style='color:red' id='usernameErrorSection'></span><br><br>\r\n");
      out.write("Password  \r\n");
      out.write("<input type='password' id='password' name='password' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${administratorBean.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'  maxlength='20'>\r\n");
      out.write("<span style='color:red' id='passwordErrorSection'></span><br><br><br>\r\n");
      out.write("<button type='submit'>Login</button>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</div><!-- Inner panel ends here -->\r\n");
      out.write("</div><!-- Container section ends here -->\r\n");
      out.write("<!-- Footer starts here -->\r\n");
      out.write("<div style='width:90hw;height:auto;margin:5px;text-align:center;border:1px solid white'>\r\n");
      out.write("&copy; ABS Company 2022\r\n");
      out.write("</div><!-- Footer ends here -->\r\n");
      out.write("</div> <!-- Main container ends here -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
